# -*- coding: utf-8 -*-
"""Restaurant_Review_ABSA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6yRkdoY1QSyzMvET0FYlf0hZ946IrnY

**INTRODUCTION**

**This project implements Aspect-Based Sentiment Analysis (ABSA) on restaurant reviews. Each review contains one or more aspects such as food taste, service, ambience, or behaviour along with their corresponding sentiment labels. The reviews are preprocessed, converted into TF-IDF features, and a machine learning model is trained to classify the sentiment of each aspect as Positive, Negative, or Neutral.**

**PART 1 – Install Required Libraries**
"""

# ==========================================
# PART 1 : INSTALL REQUIRED LIBRARIES
# ==========================================

# Install NLP Libraries
!pip install -q nltk
!pip install -q spacy
!pip install -q gensim
!pip install -q transformers
!pip install -q sentencepiece
!pip install -q wordcloud

# Download SpaCy English Model
!python -m spacy download en_core_web_sm

# ==========================================
# DOWNLOAD NLTK DATASETS
# ==========================================

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('vader_lexicon')

# ==========================================
# VERIFY INSTALLATION
# ==========================================

import pandas as pd
import numpy as np
import sklearn
import nltk
import spacy
import gensim
import transformers
import matplotlib
import seaborn

print("All libraries installed successfully.")

"""**PART 2 – Import Required Libraries**"""

# ==========================================================
# PART 2 : IMPORT REQUIRED LIBRARIES
# ==========================================================

# -----------------------------
# Basic Libraries
# -----------------------------
import pandas as pd
import numpy as np

# -----------------------------
# Data Visualization
# -----------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# Text Processing
# -----------------------------
import re
import string

# -----------------------------
# NLTK Libraries
# -----------------------------
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

# -----------------------------
# SpaCy
# -----------------------------
import spacy

# Load English Language Model
nlp = spacy.load("en_core_web_sm")

# -----------------------------
# Machine Learning
# -----------------------------
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression

from sklearn.svm import LinearSVC

from sklearn.ensemble import RandomForestClassifier

from sklearn.naive_bayes import MultinomialNB

# -----------------------------
# Evaluation Metrics
# -----------------------------
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# -----------------------------
# Word2Vec
# -----------------------------
from gensim.models import Word2Vec

# -----------------------------
# BERT
# -----------------------------
from transformers import (
    BertTokenizer,
    BertModel,
    BertForSequenceClassification
)

import torch

# -----------------------------
# WordCloud
# -----------------------------
from wordcloud import WordCloud

# -----------------------------
# Ignore Warnings
# -----------------------------
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# Display Settings
# -----------------------------
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

print("="*60)
print("All Libraries Imported Successfully")
print("="*60)

"""**PART 3 – Load Dataset & Basic Information (EDA Step 1)**"""

# ==========================================================
# PART 3 : LOAD DATASET & BASIC EXPLORATORY DATA ANALYSIS
# ==========================================================

# -----------------------------
# Upload Dataset
# -----------------------------
from google.colab import files
import pandas as pd

uploaded = files.upload()

# Replace with your dataset name if different
df = pd.read_csv("Processed_Queries_and_Reviews_Annotated_Data_Final.csv")

print("="*60)
print("DATASET LOADED SUCCESSFULLY")
print("="*60)

# ==========================================================
# Dataset Shape
# ==========================================================

print("\nDataset Shape")
print("-"*40)
print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])

# ==========================================================
# Column Names
# ==========================================================

print("\nColumn Names")
print("-"*40)
print(df.columns.tolist())

# ==========================================================
# First Five Rows
# ==========================================================

print("\nFirst Five Rows")
print("-"*40)
display(df.head())

# ==========================================================
# Last Five Rows
# ==========================================================

print("\nLast Five Rows")
print("-"*40)
display(df.tail())

# ==========================================================
# Dataset Information
# ==========================================================

print("\nDataset Information")
print("-"*40)
df.info()

# ==========================================================
# Data Types
# ==========================================================

print("\nData Types")
print("-"*40)
display(df.dtypes)

# ==========================================================
# Missing Values
# ==========================================================

print("\nMissing Values")
print("-"*40)
display(df.isnull().sum())

# Missing Percentage

print("\nMissing Value Percentage")
print("-"*40)
display((df.isnull().sum()/len(df))*100)

# ==========================================================
# Duplicate Records
# ==========================================================

duplicates = df.duplicated().sum()

print("\nDuplicate Records")
print("-"*40)
print("Total Duplicate Rows :", duplicates)

# Remove Duplicates

df = df.drop_duplicates()

print("Dataset Shape After Removing Duplicates :", df.shape)

# ==========================================================
# Statistical Summary
# ==========================================================

print("\nStatistical Summary")
print("-"*40)
display(df.describe(include='all'))

# ==========================================================
# Random Sample
# ==========================================================

print("\nRandom Sample")
print("-"*40)
display(df.sample(5, random_state=42))

# ==========================================================
# Unique Sentiments
# ==========================================================

print("\nUnique Sentiment Labels")
print("-"*40)

if 'SENTIMENT' in df.columns:
    print(df['SENTIMENT'].unique())
else:
    print("Column 'SENTIMENT' not found.")

# ==========================================================
# Sentiment Distribution
# ==========================================================

print("\nSentiment Distribution")
print("-"*40)

if 'SENTIMENT' in df.columns:
    display(df['SENTIMENT'].value_counts())
else:
    print("Column 'SENTIMENT' not found.")

# ==========================================================
# Aspect Category Distribution
# ==========================================================

print("\nAspect Category Distribution")
print("-"*40)

if 'ASPECT CATEGORY' in df.columns:
    display(df['ASPECT CATEGORY'].value_counts())
else:
    print("Column 'ASPECT CATEGORY' not found.")

# ==========================================================
# Display One Example Review
# ==========================================================

print("\nExample Review")
print("-"*40)

index = 0

if 'SENTENCE' in df.columns:
    print("Review:")
    print(df.loc[index, 'SENTENCE'])

if 'ASPECTS' in df.columns:
    print("\nAspect:")
    print(df.loc[index, 'ASPECTS'])

if 'ASPECT CATEGORY' in df.columns:
    print("\nAspect Category:")
    print(df.loc[index, 'ASPECT CATEGORY'])

if 'SENTIMENT' in df.columns:
    print("\nSentiment:")
    print(df.loc[index, 'SENTIMENT'])

print("\n" + "="*60)
print("PART 3 COMPLETED SUCCESSFULLY")
print("="*60)

"""**PART 4 – Exploratory Data Analysis (EDA)**"""

# ==========================================================
# PART 4 : EXPLORATORY DATA ANALYSIS (EDA)
# ==========================================================

import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

# Set plot style
plt.style.use("ggplot")

# ==========================================================
# 1. Sentiment Distribution (Bar Chart)
# ==========================================================

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x='SENTIMENT',
    order=df['SENTIMENT'].value_counts().index,
    palette='Set2'
)

plt.title("Sentiment Distribution", fontsize=16)
plt.xlabel("Sentiment")
plt.ylabel("Count")

for i, value in enumerate(df['SENTIMENT'].value_counts()):
    plt.text(i, value+5, str(value), ha='center', fontsize=11)

plt.show()

# ==========================================================
# 2. Sentiment Distribution (Pie Chart)
# ==========================================================

plt.figure(figsize=(7,7))

df['SENTIMENT'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    startangle=90,
    shadow=True
)

plt.title("Sentiment Percentage")
plt.ylabel("")
plt.show()

# ==========================================================
# 3. Top 15 Aspect Categories
# ==========================================================

plt.figure(figsize=(12,6))

df['ASPECT CATEGORY'].value_counts().head(15).plot(
    kind='bar',
    color='skyblue'
)

plt.title("Top 15 Aspect Categories")
plt.xlabel("Aspect Category")
plt.ylabel("Frequency")

plt.xticks(rotation=45)

plt.show()

# ==========================================================
# 4. Top 20 Aspects
# ==========================================================

plt.figure(figsize=(12,6))

df['ASPECTS'].value_counts().head(20).plot(
    kind='bar',
    color='orange'
)

plt.title("Top 20 Frequently Occurring Aspects")
plt.xlabel("Aspect")
plt.ylabel("Frequency")

plt.xticks(rotation=60)

plt.show()

# ==========================================================
# 5. Review Length Distribution
# ==========================================================

df['Review_Length'] = df['SENTENCE'].astype(str).apply(len)

plt.figure(figsize=(10,5))

sns.histplot(
    df['Review_Length'],
    bins=40,
    kde=True,
    color='purple'
)

plt.title("Distribution of Review Length")
plt.xlabel("Characters")
plt.ylabel("Frequency")

plt.show()

# ==========================================================
# 6. Review Length Boxplot
# ==========================================================

plt.figure(figsize=(8,3))

sns.boxplot(
    x=df['Review_Length'],
    color='lightgreen'
)

plt.title("Review Length Boxplot")

plt.show()

# ==========================================================
# 7. Word Cloud
# ==========================================================

text = " ".join(df['SENTENCE'].astype(str))

wordcloud = WordCloud(
    width=1200,
    height=600,
    background_color='white'
).generate(text)

plt.figure(figsize=(15,7))

plt.imshow(wordcloud)

plt.axis("off")

plt.title("Word Cloud of Reviews")

plt.show()

# ==========================================================
# 8. Top 20 Most Frequent Words
# ==========================================================

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')

X = vectorizer.fit_transform(df['SENTENCE'])

word_counts = X.sum(axis=0)

words = vectorizer.get_feature_names_out()

counts = word_counts.A1

word_df = (
    pd.DataFrame({
        'Word': words,
        'Count': counts
    })
    .sort_values(by='Count', ascending=False)
    .head(20)
)

plt.figure(figsize=(12,6))

sns.barplot(
    data=word_df,
    x='Count',
    y='Word',
    palette='viridis'
)

plt.title("Top 20 Most Frequent Words")

plt.show()

# ==========================================================
# 9. Aspect Category vs Sentiment
# ==========================================================

plt.figure(figsize=(14,7))

sns.countplot(
    data=df,
    x='ASPECT CATEGORY',
    hue='SENTIMENT'
)

plt.xticks(rotation=70)

plt.title("Aspect Category vs Sentiment")

plt.show()

# ==========================================================
# 10. Dataset Summary
# ==========================================================

print("="*60)
print("EDA SUMMARY")
print("="*60)

print("Total Reviews :", len(df))
print("Unique Aspects :", df['ASPECTS'].nunique())
print("Unique Aspect Categories :", df['ASPECT CATEGORY'].nunique())
print("Unique Sentiments :", df['SENTIMENT'].nunique())

print("\nSentiment Counts")
print(df['SENTIMENT'].value_counts())

print("\nTop 10 Aspect Categories")
print(df['ASPECT CATEGORY'].value_counts().head(10))

print("\nTop 10 Aspects")
print(df['ASPECTS'].value_counts().head(10))

print("="*60)
print("PART 4 COMPLETED SUCCESSFULLY")
print("="*60)

"""**PART 5 – Text Preprocessing**"""

# ==========================================================
# PART 5 : TEXT PREPROCESSING
# ==========================================================

import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# ----------------------------------------------------------
# Initialize Stopwords and Lemmatizer
# ----------------------------------------------------------

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# ----------------------------------------------------------
# Text Cleaning Function
# ----------------------------------------------------------

def preprocess_text(text):

    # Convert to string
    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove Numbers
    text = re.sub(r'\d+', '', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # Tokenization
    words = word_tokenize(text)

    # Remove Stopwords
    words = [word for word in words if word not in stop_words]

    # Lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    # Join words
    cleaned_text = " ".join(words)

    return cleaned_text

# ----------------------------------------------------------
# Apply Cleaning Function
# ----------------------------------------------------------

df['Cleaned_Review'] = df['SENTENCE'].apply(preprocess_text)

print("Text Preprocessing Completed Successfully!")

# ==========================================================
# Display Original vs Cleaned Reviews
# ==========================================================

comparison = df[['SENTENCE','Cleaned_Review']].head(10)

display(comparison)

# ==========================================================
# Check for Missing Values
# ==========================================================

print("\nMissing Values in Cleaned Review:")

print(df['Cleaned_Review'].isnull().sum())

# ==========================================================
# Review Length Before Cleaning
# ==========================================================

df['Original_Length'] = df['SENTENCE'].astype(str).apply(len)

# ==========================================================
# Review Length After Cleaning
# ==========================================================

df['Cleaned_Length'] = df['Cleaned_Review'].astype(str).apply(len)

# ==========================================================
# Display Length Comparison
# ==========================================================

length_df = df[['Original_Length','Cleaned_Length']]

display(length_df.head(10))

# ==========================================================
# Summary Statistics
# ==========================================================

print("\nAverage Original Review Length :",
      round(df['Original_Length'].mean(),2))

print("Average Cleaned Review Length :",
      round(df['Cleaned_Length'].mean(),2))

# ==========================================================
# Display Sample Cleaned Reviews
# ==========================================================

print("\nSample Cleaned Reviews\n")

for i in range(5):

    print("Original Review:")
    print(df.loc[i,'SENTENCE'])

    print("\nCleaned Review:")
    print(df.loc[i,'Cleaned_Review'])

    print("-"*70)

# ==========================================================
# Most Frequent Words
# ==========================================================

from collections import Counter

all_words = " ".join(df['Cleaned_Review']).split()

counter = Counter(all_words)

top_words = pd.DataFrame(counter.most_common(20),
                         columns=['Word','Frequency'])

print("\nTop 20 Frequent Words")

display(top_words)

# ==========================================================
# Save Cleaned Dataset
# ==========================================================

df.to_csv("Cleaned_ABSA_Dataset.csv", index=False)

print("\nCleaned dataset saved successfully!")

# ==========================================================
# Final Dataset Columns
# ==========================================================

print("\nDataset Columns")

print(df.columns)

print("\nDataset Shape")

print(df.shape)

print("="*60)
print("PART 5 COMPLETED SUCCESSFULLY")
print("="*60)

"""**PART 6 – POS Tagging & Aspect Extraction**"""

# ==========================================================
# PART 6 : POS TAGGING & ASPECT EXTRACTION
# ==========================================================

import nltk
import spacy
import pandas as pd

from nltk.tokenize import word_tokenize
from nltk import pos_tag

# Load SpaCy Model
nlp = spacy.load("en_core_web_sm")

# ==========================================================
# Function 1 : Extract Aspects (Nouns)
# ==========================================================

def extract_aspects(text):

    words = word_tokenize(str(text))

    tagged_words = pos_tag(words)

    aspects = []

    for word, tag in tagged_words:

        # NN = Noun
        # NNS = Plural Noun
        # NNP = Proper Noun
        # NNPS = Proper Plural Noun

        if tag in ['NN','NNS','NNP','NNPS']:

            aspects.append(word)

    return list(set(aspects))

# ==========================================================
# Function 2 : Extract Opinion Words (Adjectives)
# ==========================================================

def extract_opinion_words(text):

    words = word_tokenize(str(text))

    tagged_words = pos_tag(words)

    opinions = []

    for word, tag in tagged_words:

        # JJ = Adjective
        # JJR = Comparative
        # JJS = Superlative

        if tag in ['JJ','JJR','JJS']:

            opinions.append(word)

    return list(set(opinions))

# ==========================================================
# Function 3 : POS Tagging
# ==========================================================

def get_pos_tags(text):

    words = word_tokenize(str(text))

    return pos_tag(words)

# ==========================================================
# Apply POS Tagging
# ==========================================================

df["POS_Tags"] = df["Cleaned_Review"].apply(get_pos_tags)

# ==========================================================
# Extract Aspects
# ==========================================================

df["Extracted_Aspects"] = df["Cleaned_Review"].apply(extract_aspects)

# ==========================================================
# Extract Opinion Words
# ==========================================================

df["Opinion_Words"] = df["Cleaned_Review"].apply(extract_opinion_words)

# ==========================================================
# SpaCy Named Entity Recognition (Optional)
# ==========================================================

def extract_entities(text):

    doc = nlp(str(text))

    entities = []

    for ent in doc.ents:

        entities.append((ent.text, ent.label_))

    return entities

df["Named_Entities"] = df["Cleaned_Review"].apply(extract_entities)

# ==========================================================
# Display Results
# ==========================================================

print("="*70)
print("POS TAGGING & ASPECT EXTRACTION")
print("="*70)

display(df[['Cleaned_Review',
            'Extracted_Aspects',
            'Opinion_Words']].head(10))

# ==========================================================
# Compare Original vs Extracted Aspect
# ==========================================================

comparison = df[['ASPECTS',
                 'Extracted_Aspects',
                 'SENTIMENT']].head(15)

display(comparison)

# ==========================================================
# Show POS Tags of First Review
# ==========================================================

print("\nPOS Tags of First Review\n")

print(df.loc[0,'POS_Tags'])

# ==========================================================
# Show Extracted Aspects
# ==========================================================

print("\nExtracted Aspects\n")

for i in range(5):

    print("Review :", i+1)

    print(df.loc[i,'Cleaned_Review'])

    print("Extracted Aspects :")

    print(df.loc[i,'Extracted_Aspects'])

    print("Opinion Words :")

    print(df.loc[i,'Opinion_Words'])

    print("-"*70)

# ==========================================================
# Total Unique Extracted Aspects
# ==========================================================

all_aspects = []

for aspect_list in df["Extracted_Aspects"]:

    all_aspects.extend(aspect_list)

unique_aspects = sorted(set(all_aspects))

print("\nTotal Unique Extracted Aspects :", len(unique_aspects))

print("\nFirst 50 Unique Aspects")

print(unique_aspects[:50])

# ==========================================================
# Aspect Frequency
# ==========================================================

from collections import Counter

aspect_counter = Counter(all_aspects)

aspect_df = pd.DataFrame(

    aspect_counter.items(),

    columns=["Aspect","Frequency"]

)

aspect_df = aspect_df.sort_values(

    by="Frequency",

    ascending=False

)

print("\nTop 20 Extracted Aspects")

display(aspect_df.head(20))

# ==========================================================
# Save Updated Dataset
# ==========================================================

df.to_csv(

    "ABSA_POS_Tagged_Dataset.csv",

    index=False

)

print("\nDataset Saved Successfully!")

print("="*70)
print("PART 6 COMPLETED SUCCESSFULLY")
print("="*70)

"""**PART 7 – TF-IDF Feature Extraction**"""

# ==========================================================
# PART 7 : TF-IDF FEATURE EXTRACTION
# ==========================================================

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np

print("="*70)
print("TF-IDF FEATURE EXTRACTION")
print("="*70)

# ==========================================================
# Define Input and Target
# ==========================================================

X_text = df["Cleaned_Review"]

y = df["SENTIMENT"]

print("\nNumber of Reviews :", len(X_text))
print("Number of Labels :", len(y))

# ==========================================================
# Create TF-IDF Vectorizer
# ==========================================================

tfidf = TfidfVectorizer(

    max_features=5000,

    ngram_range=(1,2),

    min_df=2,

    max_df=0.90,

    stop_words='english'

)

# ==========================================================
# Transform Text into TF-IDF Matrix
# ==========================================================

X_tfidf = tfidf.fit_transform(X_text)

print("\nTF-IDF Matrix Created Successfully!")

print("\nMatrix Shape")

print(X_tfidf.shape)

# ==========================================================
# Feature Names
# ==========================================================

feature_names = tfidf.get_feature_names_out()

print("\nTotal TF-IDF Features :")

print(len(feature_names))

print("\nFirst 50 Features")

print(feature_names[:50])

# ==========================================================
# Convert Sparse Matrix to DataFrame
# ==========================================================

tfidf_df = pd.DataFrame(

    X_tfidf.toarray(),

    columns=feature_names

)

print("\nTF-IDF DataFrame Shape")

print(tfidf_df.shape)

# ==========================================================
# Display First Five Rows
# ==========================================================

display(tfidf_df.head())

# ==========================================================
# Top TF-IDF Features
# ==========================================================

feature_scores = np.asarray(X_tfidf.mean(axis=0)).ravel()

feature_importance = pd.DataFrame({

    "Feature": feature_names,

    "Average_TFIDF": feature_scores

})

feature_importance = feature_importance.sort_values(

    by="Average_TFIDF",

    ascending=False

)

print("\nTop 20 Important TF-IDF Features")

display(feature_importance.head(20))

# ==========================================================
# Visualize Top Features
# ==========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.barh(

    feature_importance.head(20)["Feature"][::-1],

    feature_importance.head(20)["Average_TFIDF"][::-1]

)

plt.title("Top 20 TF-IDF Features")

plt.xlabel("Average TF-IDF Score")

plt.ylabel("Feature")

plt.tight_layout()

plt.show()

# ==========================================================
# TF-IDF Sparsity
# ==========================================================

total_elements = X_tfidf.shape[0] * X_tfidf.shape[1]

non_zero = X_tfidf.count_nonzero()

sparsity = (1 - (non_zero / total_elements)) * 100

print("\nTF-IDF Sparsity")

print(f"{sparsity:.2f}%")

# ==========================================================
# Save TF-IDF Matrix
# ==========================================================

tfidf_df.to_csv(

    "TFIDF_Features.csv",

    index=False

)

print("\nTF-IDF Features Saved Successfully!")

# ==========================================================
# Store Variables for ML Models
# ==========================================================

X = X_tfidf

Y = y

print("\nMachine Learning Dataset Ready")

print("X Shape :", X.shape)

print("Y Shape :", Y.shape)

print("="*70)
print("PART 7 COMPLETED SUCCESSFULLY")
print("="*70)

"""**PART 8 – Word2Vec Feature Extraction**"""

# ==========================================================
# PART 8 : WORD2VEC FEATURE EXTRACTION
# ==========================================================

from gensim.models import Word2Vec
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize
import matplotlib.pyplot as plt
import nltk

nltk.download('punkt')

print("="*70)
print("PART 8 : WORD2VEC FEATURE EXTRACTION")
print("="*70)

# ==========================================================
# Step 1 : Tokenize Reviews
# ==========================================================

tokenized_reviews = df["SENTENCE"].astype(str).str.lower().apply(word_tokenize)

print("\nSample Tokenized Review:\n")
print(tokenized_reviews.iloc[0])

# ==========================================================
# Step 2 : Train Word2Vec Model
# ==========================================================

word2vec_model = Word2Vec(
    sentences=tokenized_reviews,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1,
    epochs=20,
    seed=42
)

print("\nWord2Vec Model Trained Successfully!")

# ==========================================================
# Step 3 : Vocabulary Size
# ==========================================================

print("\nVocabulary Size :", len(word2vec_model.wv))

# ==========================================================
# Step 4 : Check Similar Words
# ==========================================================

sample_words = [
    "food",
    "service",
    "taste",
    "staff",
    "restaurant"
]

for word in sample_words:

    if word in word2vec_model.wv:

        print(f"\nTop Similar Words for '{word}'")

        similar_words = word2vec_model.wv.most_similar(
            word,
            topn=5
        )

        for w, score in similar_words:

            print(f"{w:15s} {score:.4f}")

# ==========================================================
# Step 5 : Sentence Vector Function
# ==========================================================

def sentence_vector(sentence):

    words = word_tokenize(str(sentence).lower())

    vectors = []

    for word in words:

        if word in word2vec_model.wv:

            vectors.append(word2vec_model.wv[word])

    if len(vectors) == 0:

        return np.zeros(100)

    return np.mean(vectors, axis=0)

# ==========================================================
# Step 6 : Generate Sentence Vectors
# ==========================================================

X_word2vec = np.array(

    df["SENTENCE"]

    .apply(sentence_vector)

    .tolist()

)

print("\nWord2Vec Feature Matrix Shape")

print(X_word2vec.shape)

# ==========================================================
# Step 7 : Convert to DataFrame
# ==========================================================

word2vec_df = pd.DataFrame(X_word2vec)

print("\nFirst Five Word2Vec Vectors")

display(word2vec_df.head())

# ==========================================================
# Step 8 : Statistics
# ==========================================================

print("\nFeature Statistics")

display(word2vec_df.describe())

# ==========================================================
# Step 9 : Plot First Review Vector
# ==========================================================

plt.figure(figsize=(14,4))

plt.plot(X_word2vec[0])

plt.title("Word2Vec Vector of First Review")

plt.xlabel("Embedding Dimension")

plt.ylabel("Value")

plt.grid(True)

plt.show()

# ==========================================================
# Step 10 : Average Vector Magnitude
# ==========================================================

vector_norm = np.linalg.norm(
    X_word2vec,
    axis=1
)

print("\nAverage Vector Magnitude")

print(round(vector_norm.mean(),4))

# ==========================================================
# Step 11 : Save Features
# ==========================================================

word2vec_df.to_csv(

    "Word2Vec_Features.csv",

    index=False

)

print("\nWord2Vec Features Saved Successfully!")

# ==========================================================
# Step 12 : Prepare ML Variables
# ==========================================================

X_W2V = X_word2vec

Y_W2V = df["SENTIMENT"]

print("\nMachine Learning Dataset Ready")

print("X Shape :", X_W2V.shape)

print("Y Shape :", Y_W2V.shape)

# ==========================================================
# Step 13 : Comparison
# ==========================================================

comparison = pd.DataFrame({

    "Feature Extraction":[

        "TF-IDF",

        "Word2Vec"

    ],

    "Feature Shape":[

        str(X.shape),

        str(X_W2V.shape)

    ]

})

print("\nComparison of Feature Extraction Techniques")

display(comparison)

print("="*70)
print("PART 8 COMPLETED SUCCESSFULLY")
print("="*70)

"""**PART 9 – BERT Feature Extraction**"""

# ==========================================================
# PART 9 : BERT FEATURE EXTRACTION
# ==========================================================

from sentence_transformers import SentenceTransformer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("="*70)
print("PART 9 : BERT FEATURE EXTRACTION")
print("="*70)

# ----------------------------------------------------------
# Load Pre-trained BERT Model
# ----------------------------------------------------------

model = SentenceTransformer('all-MiniLM-L6-v2')

print("\nBERT Model Loaded Successfully!")

# ----------------------------------------------------------
# Generate Sentence Embeddings
# ----------------------------------------------------------

reviews = df["SENTENCE"].astype(str).tolist()

bert_embeddings = model.encode(

    reviews,

    show_progress_bar=True

)

print("\nBERT Embeddings Generated!")

# ----------------------------------------------------------
# Shape
# ----------------------------------------------------------

print("\nEmbedding Shape")

print(bert_embeddings.shape)

# ----------------------------------------------------------
# Convert to DataFrame
# ----------------------------------------------------------

bert_df = pd.DataFrame(bert_embeddings)

print("\nFirst Five Embeddings")

display(bert_df.head())

# ----------------------------------------------------------
# Statistics
# ----------------------------------------------------------

print("\nEmbedding Statistics")

display(bert_df.describe())

# ----------------------------------------------------------
# Plot First Review Embedding
# ----------------------------------------------------------

plt.figure(figsize=(15,4))

plt.plot(bert_embeddings[0])

plt.title("BERT Embedding (First Review)")

plt.xlabel("Embedding Dimension")

plt.ylabel("Value")

plt.grid(True)

plt.show()

# ----------------------------------------------------------
# Vector Magnitude
# ----------------------------------------------------------

norm = np.linalg.norm(

    bert_embeddings,

    axis=1

)

print("\nAverage Embedding Magnitude")

print(round(norm.mean(),4))

# ----------------------------------------------------------
# Save Features
# ----------------------------------------------------------

bert_df.to_csv(

    "BERT_Features.csv",

    index=False

)

print("\nBERT Features Saved Successfully!")

# ----------------------------------------------------------
# Prepare ML Variables
# ----------------------------------------------------------

X_BERT = bert_embeddings

Y_BERT = df["SENTIMENT"]

print("\nMachine Learning Dataset Ready")

print("X Shape :", X_BERT.shape)

print("Y Shape :", Y_BERT.shape)

# ----------------------------------------------------------
# Compare Feature Extraction Techniques
# ----------------------------------------------------------

comparison = pd.DataFrame({

    "Feature Extraction":[

        "TF-IDF",

        "Word2Vec",

        "BERT"

    ],

    "Feature Shape":[

        str(X.shape),

        str(X_W2V.shape),

        str(X_BERT.shape)

    ]

})

print("\nComparison of Feature Extraction Techniques")

display(comparison)

print("="*70)
print("PART 9 COMPLETED SUCCESSFULLY")
print("="*70)

"""**PART 10 – Prepare Aspect-Level Dataset**"""

label_encoder = LabelEncoder()

# ----------------------------------------------------------
# Clean Incorrect Sentiment Labels
# ----------------------------------------------------------

aspect_df["SENTIMENT"] = aspect_df["SENTIMENT"].str.strip()

aspect_df["SENTIMENT"] = aspect_df["SENTIMENT"].replace({
    'POSITIVE"': 'POSITIVE',
    'POSITIVE"345315': 'POSITIVE'
})

print("Sentiment Distribution After Cleaning")

print(aspect_df["SENTIMENT"].value_counts())

# ==========================================================
# PART 10 : CREATE ASPECT-LEVEL DATASET
# ==========================================================

import pandas as pd
import ast
from sklearn.preprocessing import LabelEncoder

print("="*70)
print("PART 10 : CREATE ASPECT-LEVEL DATASET")
print("="*70)

# ----------------------------------------------------------
# Select Required Columns
# ----------------------------------------------------------

aspect_df = df[[
    "SENTENCE",
    "ASPECTS",
    "SENTIMENT"
]].copy()

# ----------------------------------------------------------
# Convert String Lists to Python Lists
# ----------------------------------------------------------

def convert_to_list(value):

    if pd.isna(value):
        return []

    try:
        return ast.literal_eval(str(value))
    except:
        return [str(value)]

aspect_df["ASPECTS"] = aspect_df["ASPECTS"].apply(convert_to_list)
aspect_df["SENTIMENT"] = aspect_df["SENTIMENT"].apply(convert_to_list)

# ----------------------------------------------------------
# Create Aspect-Level Records
# ----------------------------------------------------------

rows = []

for _, row in aspect_df.iterrows():

    sentence = row["SENTENCE"]
    aspects = row["ASPECTS"]
    sentiments = row["SENTIMENT"]

    n = min(len(aspects), len(sentiments))

    for i in range(n):

        rows.append({

            "Review": sentence,
            "Aspect": aspects[i],
            "Sentiment": sentiments[i]

        })

aspect_df = pd.DataFrame(rows)

print("\nAspect-Level Dataset Created Successfully!")

print("Shape :", aspect_df.shape)

# ----------------------------------------------------------
# Remove Missing Values
# ----------------------------------------------------------

aspect_df.dropna(inplace=True)

aspect_df.reset_index(drop=True, inplace=True)

# ----------------------------------------------------------
# Create Review + Aspect Feature
# ----------------------------------------------------------

aspect_df["Review_Aspect"] = (

    aspect_df["Review"]

    + " [ASPECT] "

    + aspect_df["Aspect"]

)

# ----------------------------------------------------------
# Encode Sentiment Labels
# ----------------------------------------------------------

label_encoder = LabelEncoder()

aspect_df["Label"] = label_encoder.fit_transform(

    aspect_df["Sentiment"]

)

print("\nSentiment Classes")

print(label_encoder.classes_)

# ----------------------------------------------------------
# Dataset Preview
# ----------------------------------------------------------

display(aspect_df.head(10))

# ----------------------------------------------------------
# Sentiment Distribution
# ----------------------------------------------------------

print("\nSentiment Distribution")

display(aspect_df["Sentiment"].value_counts())

# ----------------------------------------------------------
# Top Aspects
# ----------------------------------------------------------

print("\nTop 20 Aspects")

display(

    aspect_df["Aspect"]

    .value_counts()

    .head(20)

)

# ----------------------------------------------------------
# Save Dataset
# ----------------------------------------------------------

aspect_df.to_csv(

    "Aspect_Level_Dataset.csv",

    index=False

)

print("\nDataset Saved Successfully!")

print("Aspect_Level_Dataset.csv")

print("="*70)
print("PART 10 COMPLETED SUCCESSFULLY")
print("="*70)

print(aspect_df.columns)

print(aspect_df.head())

# ----------------------------------------------------------
# Clean Sentiment Labels
# ----------------------------------------------------------

aspect_df["Sentiment"] = aspect_df["Sentiment"].str.strip()

aspect_df["Sentiment"] = aspect_df["Sentiment"].replace({
    'POSITIVE"': 'POSITIVE',
    'POSITIVE"345315': 'POSITIVE'
})

print("\nSentiment Distribution After Cleaning")

print(aspect_df["Sentiment"].value_counts())

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

aspect_df["Label"] = label_encoder.fit_transform(
    aspect_df["Sentiment"]
)

print(label_encoder.classes_)

print(label_encoder.classes_)

print(aspect_df["Sentiment"].value_counts())

"""**PART 11 – TF-IDF + Train-Test Split (Aspect-Level)**"""

# ==========================================================
# PART 11 : TF-IDF FEATURE EXTRACTION + TRAIN TEST SPLIT
# ==========================================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import joblib
import pandas as pd
import numpy as np

print("="*70)
print("PART 11 : TF-IDF FEATURE EXTRACTION")
print("="*70)

# ----------------------------------------------------------
# Input Feature
# ----------------------------------------------------------

X_text = aspect_df["Review_Aspect"]

# ----------------------------------------------------------
# Target Variable
# ----------------------------------------------------------

y = aspect_df["Label"]

# ----------------------------------------------------------
# TF-IDF Vectorizer
# ----------------------------------------------------------

tfidf = TfidfVectorizer(

    max_features=5000,

    stop_words='english',

    ngram_range=(1,2),

    min_df=2

)

# ----------------------------------------------------------
# Generate TF-IDF Features
# ----------------------------------------------------------

X = tfidf.fit_transform(X_text)

print("\nTF-IDF Matrix Created Successfully!")

print("Shape :", X.shape)

# ----------------------------------------------------------
# Feature Names
# ----------------------------------------------------------

feature_names = tfidf.get_feature_names_out()

print("\nTotal Features :", len(feature_names))

print("\nFirst 20 Features")

print(feature_names[:20])

# ----------------------------------------------------------
# Top Important Features
# ----------------------------------------------------------

scores = np.asarray(X.mean(axis=0)).ravel()

importance = pd.DataFrame({

    "Feature":feature_names,

    "Average TF-IDF":scores

})

importance = importance.sort_values(

    by="Average TF-IDF",

    ascending=False

)

print("\nTop 20 Important Features")

display(importance.head(20))

# ----------------------------------------------------------
# Train Test Split
# ----------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

print("\nTrain-Test Split Completed Successfully!")

print("\nTraining Shape :", X_train.shape)

print("Testing Shape :", X_test.shape)

# ----------------------------------------------------------
# Class Distribution
# ----------------------------------------------------------

print("\nTraining Class Distribution")

print(pd.Series(y_train).value_counts())

print("\nTesting Class Distribution")

print(pd.Series(y_test).value_counts())

# ----------------------------------------------------------
# Save TF-IDF Model
# ----------------------------------------------------------

joblib.dump(

    tfidf,

    "tfidf_vectorizer.pkl"

)

joblib.dump(

    label_encoder,

    "label_encoder.pkl"

)

print("\nModels Saved Successfully!")

# ----------------------------------------------------------
# Save Feature Matrix
# ----------------------------------------------------------

tfidf_df = pd.DataFrame(

    X.toarray(),

    columns=feature_names

)

tfidf_df.to_csv(

    "TFIDF_Features.csv",

    index=False

)

print("\nTF-IDF Features Saved!")

# ----------------------------------------------------------
# Summary
# ----------------------------------------------------------

summary = pd.DataFrame({

    "Information":[

        "Total Samples",

        "Training Samples",

        "Testing Samples",

        "Total Features"

    ],

    "Value":[

        X.shape[0],

        X_train.shape[0],

        X_test.shape[0],

        X.shape[1]

    ]

})

print("\nSummary")

display(summary)

print("="*70)
print("PART 11 COMPLETED SUCCESSFULLY")
print("="*70)

print(label_encoder.classes_)

print(aspect_df["Label"].value_counts())

"""**PART 12 – Train Aspect-Level Sentiment Models**"""

# ==========================================================
# PART 12 : MODEL TRAINING
# ==========================================================

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
import pandas as pd
import joblib

print("="*70)
print("PART 12 : MODEL TRAINING")
print("="*70)

# ----------------------------------------------------------
# Initialize Models
# ----------------------------------------------------------

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        random_state=42
    ),

    "Naive Bayes": MultinomialNB(),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),

    "Linear SVM": LinearSVC(
        random_state=42
    )

}

# ----------------------------------------------------------
# Train Models
# ----------------------------------------------------------

results = []

best_model = None
best_model_name = ""
best_accuracy = 0

for name, model in models.items():

    print("\nTraining :", name)

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    print("Accuracy :", round(accuracy,4))

    results.append([

        name,

        round(accuracy,4)

    ])

    if accuracy > best_accuracy:

        best_accuracy = accuracy

        best_model = model

        best_model_name = name

# ----------------------------------------------------------
# Comparison Table
# ----------------------------------------------------------

results_df = pd.DataFrame(

    results,

    columns=[

        "Model",

        "Accuracy"

    ]

)

results_df = results_df.sort_values(

    by="Accuracy",

    ascending=False

)

print("\nModel Comparison")

display(results_df)

# ----------------------------------------------------------
# Best Model
# ----------------------------------------------------------

print("\nBest Model :", best_model_name)

print("Best Accuracy :", round(best_accuracy,4))

# ----------------------------------------------------------
# Save Best Model
# ----------------------------------------------------------

joblib.dump(

    best_model,

    "Best_ABSA_Model.pkl"

)

print("\nBest Model Saved Successfully!")

print("File : Best_ABSA_Model.pkl")

# ----------------------------------------------------------
# Summary
# ----------------------------------------------------------

summary = pd.DataFrame({

    "Information":[

        "Training Samples",

        "Testing Samples",

        "Best Model",

        "Best Accuracy"

    ],

    "Value":[

        X_train.shape[0],

        X_test.shape[0],

        best_model_name,

        round(best_accuracy,4)

    ]

})

print("\nSummary")

display(summary)

print("="*70)
print("PART 12 COMPLETED SUCCESSFULLY")
print("="*70)

"""**PART 13 – Aspect-Level Model Evaluation**"""

# ==========================================================
# PART 13 : MODEL EVALUATION
# ==========================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

import matplotlib.pyplot as plt
import pandas as pd

print("="*70)
print("PART 13 : MODEL EVALUATION")
print("="*70)

# ----------------------------------------------------------
# Predict Test Data
# ----------------------------------------------------------

y_pred = best_model.predict(X_test)

# ----------------------------------------------------------
# Calculate Metrics
# ----------------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average='weighted'
)

recall = recall_score(
    y_test,
    y_pred,
    average='weighted'
)

f1 = f1_score(
    y_test,
    y_pred,
    average='weighted'
)

# ----------------------------------------------------------
# Display Metrics
# ----------------------------------------------------------

metrics_df = pd.DataFrame({

    "Metric":[
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score"
    ],

    "Value":[
        round(accuracy,4),
        round(precision,4),
        round(recall,4),
        round(f1,4)
    ]

})

print("\nEvaluation Metrics")

display(metrics_df)

# ----------------------------------------------------------
# Classification Report
# ----------------------------------------------------------

print("\nClassification Report\n")

print(

    classification_report(

        y_test,

        y_pred,

        target_names=label_encoder.classes_

    )

)

# ----------------------------------------------------------
# Confusion Matrix
# ----------------------------------------------------------

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(

    confusion_matrix=cm,

    display_labels=label_encoder.classes_

)

plt.figure(figsize=(6,6))

disp.plot(cmap="Blues")

plt.title("Confusion Matrix")

plt.show()

# ----------------------------------------------------------
# Save Metrics
# ----------------------------------------------------------

metrics_df.to_csv(

    "Model_Evaluation_Metrics.csv",

    index=False

)

print("\nMetrics Saved Successfully!")

print("File : Model_Evaluation_Metrics.csv")

print("="*70)
print("PART 13 COMPLETED SUCCESSFULLY")
print("="*70)

"""**PART 14 – True Aspect-Based Sentiment Prediction**"""

# ==========================================================
# PART 14 : PREDICT SENTIMENT FOR NEW REVIEW
# ==========================================================

import joblib
import pandas as pd

print("="*70)
print("PART 14 : SENTIMENT PREDICTION")
print("="*70)

# ----------------------------------------------------------
# Load Saved Model
# ----------------------------------------------------------

model = joblib.load("Best_ABSA_Model.pkl")

tfidf = joblib.load("tfidf_vectorizer.pkl")

label_encoder = joblib.load("label_encoder.pkl")

print("\nModels Loaded Successfully!")

# ----------------------------------------------------------
# User Input
# ----------------------------------------------------------

review = input("\nEnter Restaurant Review : ")

aspect = input("Enter Aspect (Food/Service/Ambience/Price etc.) : ")

# ----------------------------------------------------------
# Prepare Input
# ----------------------------------------------------------

review_aspect = review + " [ASPECT] " + aspect

# ----------------------------------------------------------
# TF-IDF Transformation
# ----------------------------------------------------------

review_vector = tfidf.transform([review_aspect])

# ----------------------------------------------------------
# Prediction
# ----------------------------------------------------------

prediction = model.predict(review_vector)

sentiment = label_encoder.inverse_transform(prediction)

# ----------------------------------------------------------
# Display Result
# ----------------------------------------------------------

print("\n" + "="*50)
print("Prediction Result")
print("="*50)

print("Review    :", review)
print("Aspect    :", aspect)
print("Sentiment :", sentiment[0])


print("="*70)
print("PART 14 COMPLETED SUCCESSFULLY")
print("="*70)